### ISSUE TITLE
Add growing tree algorithm

### ISSUE THREAD

**Issue by TheWizardBear** [TheWizardBear/maze_generator#2]

**Comment by AlexRiosJ** [comment]
Hi! I would like to take this one.
One question... This Growing tree algorithm isn't the same as the recursive backtracker?

**Comment by TheWizardBear** [comment]
Great! 
> This Growing tree algorithm isn't the same as the recursive backtracker?

Sort of... it's a more generalized version of the recursive backtracker (depth-first search) algorithm. The recursive backtracker always backtracks to the newest (most recent) unexplored cell it can, but the growing tree algorithm can backtrack to different cells depending on the setting:
* newest - identical to depth-first search
* random - very similar (but not identical) to simplified Prim's
* oldest
* middle or some other proportion of the way through the list of cells that it can backtrack to
* some combination of the above

I recommend that you read [this post](http://weblog.jamisbuck.org/2011/1/27/maze-generation-growing-tree-algorithm) about the algorithm in order to familiarize yourself with it.

I haven't yet made this repo as friendly as it could be for contributors, so I recommend that you look at the files for the other algorithms (especially recursive backtracker) to get an idea of how it should be structured. The main points are:
* The `resetVariables` method is called once at the beginning. This is where you should initialize any variables not inherited from the `Maze` class.
* The  `takeStep` method is called repeatedly, every time the algorithm advances a bit. A maximum of one wall should be removed (with `removeWall`) each time it is called.
* The walls of each cell can be accessed with `.walls[y][x]` and should be modified with `.removedWall(cell, wallDirection)`
* `.finishedGenerating` should be set to `true` when the maze is finished and you should use `.currentCell` to store the current cell (as an object with `x` and `y` properties).

Since the growing tree algorithm can have multiple possible settings, you can use a placeholder variable for the cell selection method for now, until I work out how it will be passed in.

If you need any help or clarification then please let me know. :)

**Comment by TheWizardBear** [comment]
Sorry, I should have said before: If you could work off the `dev` branch, that will make merging it later eaisier.

**Comment by AlexRiosJ** [comment]
I have just created a Pull Request (#17 ) on this Issue.
So then you can link them now.

I also wanted to know how can I do testing for the changes I need to do.

Regards!

**Comment by TheWizardBear** [comment]
You should see this in version 0.4.0, which will be released soon.
